\RequirePackage{luatex85}
\ProvidesClass{tikzstandalone}
\LoadClassWithOptions{standalone}
\RequirePackage{tikz}

\RequirePackage{fontspec}
\setmainfont{Comic Sans MS}

\usetikzlibrary{calc}
\usetikzlibrary{decorations.pathreplacing}
\usetikzlibrary{decorations.pathmorphing}
\usetikzlibrary{decorations.markings}
\usetikzlibrary{arrows.meta}

\definecolor{darkgreen}{RGB}{0,128,0}

\RequirePackage{Physics}